import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_animate/flutter_animate.dart';
import '../../insights/services/financial_insight_service.dart';
import 'package:wallet/core/database/providers.dart';
import '../../insights/models/financial_insight_model.dart';
import '../../../core/design/widgets/skeleton_widgets.dart';

class InsightsScreen extends ConsumerWidget {
  const InsightsScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final transactionsAsync = ref.watch(transactionsStreamProvider);

    return Scaffold(
      appBar: AppBar(title: const Text('Financial Insights')),
      body: transactionsAsync.when(
        data: (transactions) {
          final service = ref.read(financialInsightServiceProvider);
          return FutureBuilder<FinancialInsightModel>(
            future: service.generateInsights(transactions),
            builder: (context, snapshot) {
              if (snapshot.connectionState == ConnectionState.waiting) {
                return const _LoadingView();
              }
              if (snapshot.hasError) {
                return _ErrorView(error: snapshot.error.toString());
              }
              if (!snapshot.hasData) {
                return const _ErrorView(error: "No insights generated.");
              }

              final insights = snapshot.data!;
              return ListView(
                padding: const EdgeInsets.all(16),
                children: [
                   _InsightCard(
                    title: 'Summary',
                    icon: Icons.pie_chart,
                    color: Colors.blue,
                    content: insights.summary,
                    delay: 0,
                  ),
                  _InsightCard(
                    title: 'Advice',
                    icon: Icons.lightbulb,
                    color: Colors.amber,
                    content: insights.advice,
                    delay: 100,
                  ),
                  if (insights.warning.isNotEmpty)
                    _InsightCard(
                      title: 'Attention Needed',
                      icon: Icons.warning_amber,
                      color: Colors.red,
                      content: insights.warning,
                      delay: 200,
                    ),
                    
                  const SizedBox(height: 24),
                  const Divider(),
                  ListTile(
                    leading: const Icon(Icons.privacy_tip, color: Colors.grey),
                    title: const Text('Privacy & Data'),
                    subtitle: const Text('All analysis runs locally on your device.'),
                    onTap: () => _showPrivacyDialog(context),
                  ),
                ],
              );
            },
          );
        },
        loading: () => const _LoadingView(),
        error: (err, stack) => _ErrorView(error: err.toString()),
      ),
    );
  }

  void _showPrivacyDialog(BuildContext context) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Privacy Policy'),
        content: const Text(
          "Your financial data never leaves this device.\n\n"
          "• No external AI APIs are used.\n"
          "• No cloud storage is enabled.\n"
          "• All insights are generated by an offline rule-based engine.\n\n"
          "You are in full control.",
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('OK'),
          ),
        ],
      ),
    );
  }
}

class _InsightCard extends StatelessWidget {
  final String title;
  final IconData icon;
  final Color color;
  final String content;
  final int delay;

  const _InsightCard({
    required this.title,
    required this.icon,
    required this.color,
    required this.content,
    required this.delay,
  });

  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 2,
      margin: const EdgeInsets.only(bottom: 16),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Icon(icon, color: color),
                const SizedBox(width: 8),
                Text(
                  title,
                  style: Theme.of(context).textTheme.titleMedium?.copyWith(
                        fontWeight: FontWeight.bold,
                        color: color,
                      ),
                ),
              ],
            ),
            const SizedBox(height: 8),
            Text(content, style: Theme.of(context).textTheme.bodyMedium),
          ],
        ),
      ),
    ).animate(delay: delay.ms).fade(duration: 500.ms).slideX(begin: 0.1, end: 0);
  }
}

class _LoadingView extends StatelessWidget {
  const _LoadingView();

  @override
  Widget build(BuildContext context) {
    return const Padding(
      padding: EdgeInsets.all(16.0),
      child: Column(
        children: [
          SkeletonCard(height: 120, borderRadius: BorderRadius.all(Radius.circular(16))),
          SizedBox(height: 16),
          SkeletonCard(height: 120, borderRadius: BorderRadius.all(Radius.circular(16))),
          SizedBox(height: 16),
          SkeletonCard(height: 120, borderRadius: BorderRadius.all(Radius.circular(16))),
        ],
      ),
    );
  }
}

class _ErrorView extends StatelessWidget {
  final String error;
  const _ErrorView({required this.error});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Container(
        padding: const EdgeInsets.all(16),
        color: Colors.red.shade50,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Icon(Icons.error_outline, color: Colors.red, size: 48),
            const SizedBox(height: 16),
            Text(
              'Unable to load insights',
              style: Theme.of(context).textTheme.titleMedium?.copyWith(color: Colors.red),
            ),
            const SizedBox(height: 8),
            Text(error, textAlign: TextAlign.center),
          ],
        ),
      ),
    );
  }
}
