workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      java: 17
      vars:
        PACKAGE_NAME: "com.mrdarksidetm.wallet"

    scripts:
      - name: Get Dependencies
        script: |
          flutter pub get

      - name: Patch Isar for AGP 8 Compatibility
        script: |
          echo "Patching Isar Manifest..."
          find $HOME/.pub-cache/hosted/pub.dev/isar_flutter_libs-* -name "AndroidManifest.xml" -exec sed -i '' 's/package="dev.isar.isar_flutter_libs"//g' {} + || true
          echo "Patch complete."

      - name: Run Code Generation
        script: |
          dart run build_runner build --delete-conflicting-outputs

      - name: Build Android Release
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - ajukr99901@gmail.com
        notify:
          success: true
          failure: true