workflows:
  android-release:
    name: Android Release
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Flutter Analyze
        script: |
          flutter analyze
      - name: Flutter Test
        script: |
          flutter test
      - name: Build Android Release
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
