workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      groups:
        - keystore_credentials
      flutter: stable
      java: 17

    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle

    scripts:

      - name: Initialize Flutter
        script: |
          flutter doctor -v
          flutter --version
          flutter precache

      - name: Clean Project
        script: |
          flutter clean

      - name: Get Dependencies
        script: |
          flutter pub get

      - name: Patch Isar for AGP 8 Compatibility
        script: |
          echo "Patching Isar Manifest..."
          find $HOME/.pub-cache/hosted/pub.dev/isar_flutter_libs-* \
          -name "AndroidManifest.xml" \
          -exec sed -i '' 's/package="dev.isar.isar_flutter_libs"//g' {} + || true
          echo "Patch complete."

      - name: Run Code Generation
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Static Analysis
        script: |
          flutter analyze

      - name: Configure Keystore
        script: |
          echo "$CM_KEYSTORE_BASE64" | tr -d '\n\r ' | base64 --decode > android/upload-keystore.jks

      - name: Build Android Release APKs
        script: |
          mkdir -p build/artifacts
          flutter build apk --release --split-per-abi --no-tree-shake-icons
          cp build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk build/artifacts/Wallet-armeabi-v7a.apk
          cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/artifacts/Wallet-arm64-v8a.apk
          flutter build apk --release --no-tree-shake-icons
          cp build/app/outputs/flutter-apk/app-release.apk build/artifacts/Wallet-universal.apk

    artifacts:
      - build/artifacts/*.apk

    publishing:
      email:
        recipients:
          - ajukr99901@gmail.com
