package com.darkytm.wallet.ui.theme

import androidx.compose.ui.graphics.Color

// =========================================================================
// 🎨 ALL 10 MATERIAL 3 WARM DYNAMIC PALETTES
// =========================================================================

// 1. EXPRESSIVE (Warm Amber, Spiced Cinnamon & Botanical Sage)
val ExpressivePrimaryLight = Color(0xFF8E4E00)
val ExpressiveOnPrimaryLight = Color(0xFFFFFFFF)
val ExpressivePrimaryContainerLight = Color(0xFFFFDCC1)
val ExpressiveOnPrimaryContainerLight = Color(0xFF2E1500)
val ExpressiveSecondaryLight = Color(0xFF765840)
val ExpressiveOnSecondaryLight = Color(0xFFFFFFFF)
val ExpressiveSecondaryContainerLight = Color(0xFFFFDCC2)
val ExpressiveOnSecondaryContainerLight = Color(0xFF2B1605)
val ExpressiveTertiaryLight = Color(0xFF5A633B)
val ExpressiveOnTertiaryLight = Color(0xFFFFFFFF)
val ExpressiveTertiaryContainerLight = Color(0xFFDFE9B5)
val ExpressiveOnTertiaryContainerLight = Color(0xFF171E01)
val ExpressiveBackgroundLight = Color(0xFFFFF8F4)
val ExpressiveOnBackgroundLight = Color(0xFF221A14)
val ExpressiveSurfaceLight = Color(0xFFFFF8F4)
val ExpressiveOnSurfaceLight = Color(0xFF221A14)
val ExpressiveSurfaceVariantLight = Color(0xFFF3DFD1)
val ExpressiveOnSurfaceVariantLight = Color(0xFF52443B)
val ExpressiveOutlineLight = Color(0xFF84746A)

val ExpressivePrimaryDark = Color(0xFFFFB77C)
val ExpressiveOnPrimaryDark = Color(0xFF4C2700)
val ExpressivePrimaryContainerDark = Color(0xFF6C3A00)
val ExpressiveOnPrimaryContainerDark = Color(0xFFFFDCC1)
val ExpressiveSecondaryDark = Color(0xFFE5BEA2)
val ExpressiveOnSecondaryDark = Color(0xFF432B16)
val ExpressiveSecondaryContainerDark = Color(0xFF5C412B)
val ExpressiveOnSecondaryContainerDark = Color(0xFFFFDCC2)
val ExpressiveTertiaryDark = Color(0xFFC3CD9B)
val ExpressiveOnTertiaryDark = Color(0xFF2D3411)
val ExpressiveTertiaryContainerDark = Color(0xFF434B25)
val ExpressiveOnTertiaryContainerDark = Color(0xFFDFE9B5)
val ExpressiveBackgroundDark = Color(0xFF19120C)
val ExpressiveOnBackgroundDark = Color(0xFFEFE0D7)
val ExpressiveSurfaceDark = Color(0xFF19120C)
val ExpressiveOnSurfaceDark = Color(0xFFEFE0D7)
val ExpressiveSurfaceVariantDark = Color(0xFF52443B)
val ExpressiveOnSurfaceVariantDark = Color(0xFFD6C3B6)
val ExpressiveOutlineDark = Color(0xFF9F8D82)

// 2. TONAL SPOT (Honey Caramel & Soft Almond)
val TonalSpotPrimaryLight = Color(0xFF7A5813)
val TonalSpotPrimaryDark = Color(0xFFECBF6E)
val TonalSpotSecondaryLight = Color(0xFF6B5C3F)
val TonalSpotSecondaryDark = Color(0xFFD7C4A0)
val TonalSpotTertiaryLight = Color(0xFF4C6546)
val TonalSpotTertiaryDark = Color(0xFFB1CCAA)

// 3. VIBRANT (High-Chroma Sunlit Terracotta & Molten Gold)
val VibrantPrimaryLight = Color(0xFF9E4300)
val VibrantPrimaryDark = Color(0xFFFFB590)
val VibrantSecondaryLight = Color(0xFF865320)
val VibrantSecondaryDark = Color(0xFFFBB77A)
val VibrantTertiaryLight = Color(0xFF785900)
val VibrantTertiaryDark = Color(0xFFF9BD29)

// 4. RAINBOW (Amber Gold, Sunset Coral, Sage & Copper Teal)
val RainbowPrimaryLight = Color(0xFF8B4F1A)
val RainbowPrimaryDark = Color(0xFFFFB68C)
val RainbowSecondaryLight = Color(0xFF765848)
val RainbowSecondaryDark = Color(0xFFE5BEAC)
val RainbowTertiaryLight = Color(0xFF386663)
val RainbowTertiaryDark = Color(0xFFA0D0CD)

// 5. FRUIT SALAD (Warm Apricot Peach & Refreshing Mint)
val FruitSaladPrimaryLight = Color(0xFFA13F40)
val FruitSaladPrimaryDark = Color(0xFFFFB3B3)
val FruitSaladSecondaryLight = Color(0xFF386851)
val FruitSaladSecondaryDark = Color(0xFFA0D2B8)
val FruitSaladTertiaryLight = Color(0xFF8A5100)
val FruitSaladTertiaryDark = Color(0xFFFFB870)

// 6. SPRITZ (Soft Pastel Linen, Spiced Latte & Whispering Sage)
val SpritzPrimaryLight = Color(0xFF7B5C40)
val SpritzPrimaryDark = Color(0xFFECC3A4)
val SpritzSecondaryLight = Color(0xFF6F5E53)
val SpritzSecondaryDark = Color(0xFFDDC2B4)
val SpritzTertiaryLight = Color(0xFF5E6254)
val SpritzTertiaryDark = Color(0xFFC7CBB9)

// 7. FIDELITY (True-To-Seed Deep Amber Resin & Pure Warm Ochre)
val FidelityPrimaryLight = Color(0xFF875200)
val FidelityPrimaryDark = Color(0xFFFFB868)
val FidelitySecondaryLight = Color(0xFF775924)
val FidelitySecondaryDark = Color(0xFFE6C087)
val FidelityTertiaryLight = Color(0xFF566228)
val FidelityTertiaryDark = Color(0xFFBDCD8C)

// 8. CONTENT (Sun-drenched Ochre, Baked Clay & Muted Moss)
val ContentPrimaryLight = Color(0xFF835800)
val ContentPrimaryDark = Color(0xFFFFBA38)
val ContentSecondaryLight = Color(0xFF73593D)
val ContentSecondaryDark = Color(0xFFE2C0A0)
val ContentTertiaryLight = Color(0xFF576442)
val ContentTertiaryDark = Color(0xFFBECDAB)

// 9. MONOCHROME (Warm Sepia Slate & Obsidian Charcoal)
val MonochromePrimaryLight = Color(0xFF2A2421)
val MonochromePrimaryDark = Color(0xFFEBE1DC)
val MonochromeSecondaryLight = Color(0xFF4C4440)
val MonochromeSecondaryDark = Color(0xFFCFC5C0)
val MonochromeTertiaryLight = Color(0xFF37302D)
val MonochromeTertiaryDark = Color(0xFFD5CBC6)

// 10. NEUTRAL (Warm Travertine Stone & Warm Pebble Gray)
val NeutralPrimaryLight = Color(0xFF655D56)
val NeutralPrimaryDark = Color(0xFFD0C4BC)
val NeutralSecondaryLight = Color(0xFF615D58)
val NeutralSecondaryDark = Color(0xFFCAC3BE)
val NeutralTertiaryLight = Color(0xFF635C5B)
val NeutralTertiaryDark = Color(0xFFCCC3C2)

// =========================================================================
// 🖤 AMOLED (PITCH BLACK) CONSTANTS
// =========================================================================
val BackgroundAmoled = Color(0xFF000000)
val SurfaceAmoled = Color(0xFF000000)
val SurfaceVariantAmoled = Color(0xFF140E0A)

// =========================================================================
// 📈 FINANCIAL & TRANSACTION STATUS COLORS
// =========================================================================
val IncomeGreenLight = Color(0xFF2E7D32)
val IncomeGreenDark = Color(0xFF81C784)
val ExpenseRedLight = Color(0xFFC62828)
val ExpenseRedDark = Color(0xFFFF8A80)
val TransferBlueLight = Color(0xFF1565C0)
val TransferBlueDark = Color(0xFF90CAF9)
val DebtPurpleLight = Color(0xFF6A1B9A)
val DebtPurpleDark = Color(0xFFCE93D8)
val GoalGoldLight = Color(0xFFF57F17)
val GoalGoldDark = Color(0xFFFFEE58)
